platform:ios,'8.0'

target 'IM' do
pod 'AVOSCloud' , '3.1.2.9'
pod 'AVOSCloudIM', '3.1.2.9'
pod 'Masonry'
pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', ‘3.1.0’
pod 'MJRefresh'
pod 'MJExtension'
pod 'UITableView+FDTemplateLayoutCell'
pod 'SVProgressHUD','~> 2.0.4'
pod 'pop', '~> 1.0'
pod 'MagicalRecord'
pod 'SWTableViewCell', '~> 0.3.7'
pod "GPUImage"

end
